"""Guard: the platformer curriculum contains ONLY the original SMB levels
and rule-of-thirds SLICES of them — never synthetic stage_* ramps.

History: an earlier change registered hand-authored stage_1..stage_14 ramps;
the project owner rejected them (train on real levels). Later (2026-07-10)
the owner asked for short level SLICES as a curriculum ("cut the levels
short — use the third rule"), which are genuine excerpts of the original
geometry generated by code/scripts/make_level_slices.py. Slices are allowed;
synthetic levels remain banned.
"""
import re

from code.games.platformer_core import PlatformerCore

# slices (a/b/c) must precede their full level; 1-1 track precedes 1-2 track
EXPECTED_ORDER = [
    "Mario1-1a", "Mario1-1b", "Mario1-1c", "Mario1-1",
    "Mario1-2a", "Mario1-2b", "Mario1-2c", "Mario1-2",
]
_ALLOWED = re.compile(r"^Mario1-[12][abc]?$")


def test_platformer_curriculum_is_slices_then_full_levels():
    core = PlatformerCore(render_mode="none")
    assert core.level_order == EXPECTED_ORDER, (
        f"curriculum must be rule-of-thirds slices then full originals, "
        f"got {core.level_order}"
    )


def test_only_original_levels_and_their_slices():
    core = PlatformerCore(render_mode="none")
    bad = [lvl for lvl in core.level_order if not _ALLOWED.match(str(lvl))]
    assert not bad, f"non-original levels registered: {bad}"


def test_no_synthetic_stage_levels_registered():
    core = PlatformerCore(render_mode="none")
    stages = [lvl for lvl in core.level_order if str(lvl).startswith("stage_")]
    assert not stages, f"synthetic stage_* levels must not be in the curriculum: {stages}"


def test_every_slice_is_playable():
    """Each slice must load, have a REAL goal (x > TILE_SIZE guard), and a
    Dijkstra-reachable goal from spawn — an unreachable goal would silently
    blind the adept persona and the path-stall watchdog on that level."""
    for lvl in EXPECTED_ORDER:
        core = PlatformerCore(render_mode="none", world=lvl,
                              curriculum_enabled=False)
        core.reset()
        _, _, _, _, info = core.step([0, 0, 0])
        assert core.level_data.goals, f"{lvl}: no goal entity"
        assert info.get("dijkstra_dist", -1.0) >= 0.0, (
            f"{lvl}: goal not Dijkstra-reachable from spawn"
        )
