_target_: algos.get_algo
name: ppo               # looked up inside get_algo → PPO class
policy: MlpPolicy

# --- Exploration & Memory Settings ---
n_steps: 4096
ent_coef: 0.05

# --- Standard PPO Settings ---
batch_size: 64
n_epochs: 10
learning_rate: 0.0003
gae_lambda: 0.95
gamma: 0.99
clip_range: 0.2
verbose: 1

policy_kwargs:
  optimizer_kwargs:
    weight_decay: 1e-4


device: cpu      # cpu / cuda